# Generated by Django 3.1 on 2020-08-11 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_subs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subs',
            new_name='Sub',
        ),
    ]
